services:
  node:
    container_name: countries-map-node
    image: node:23.7-slim
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
      - "${VITE_PREVIEW_PORT}:${VITE_PREVIEW_PORT}"
    volumes:
      - ./:/var/www/countries-map
    working_dir: /var/www/countries-map
    tty: true
