services:
  node:
    container_name: countries-map-node
    image: node:23.7-slim
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/countries-map
    working_dir: /var/www/countries-map
    tty: true
